apiVersion: v1
kind: Service
metadata:
  name: week-days-api-service
  namespace: week-days-ns
spec:
  selector:
    app: week-days-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
